apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - aspnetapp.yaml
patches:
  - patch: |-
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: aspnetapp
        namespace: aspnetapp
      spec:
        ingressClassName: azure-application-gateway